In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder"
response = requests.get(url)

In [3]:
soup = BeautifulSoup(response.content, "html.parser")

In [4]:
table = soup.find("table", class_="table")

In [6]:
table

<table class="table rankings-table">
<thead>
<tr class="table-head">
<th class="table-head__cell u-text-right">Pos</th>
<th class="table-head__cell">Player</th>
<th class="table-head__cell">Team</th>
<th class="table-head__cell table-head__cell--rating">Rating</th>
<th class="table-head__cell u-text-right u-hide-phablet">Career Best Rating</th>
</tr>
</thead>
<tr class="rankings-block__banner">
<td class="rankings-block__position">
<div class="rankings-block__pos-container">
<span class="rankings-block__pos-number">
                            1
                        </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="rankings-block__top-player-container">
<div class="u-flex-center u-text-left">
<div class="rankings-block__player-image-container rankings-block__player-image-container--large">
<a href="/rankings/womens/player-rankings/3126">
<img alt="Player Image" class="rankings-block__player-image image-missing" data-error="true" data-player="3126" data-size="130x150" data-widget="player-image" src="//resources.pulse.icc-cricket.com/players/130x150/Photo-Missing.png"/>
</a>
</div>
<div>
<a href="/rankings/womens/player-rankings/3126"><div class="rankings-block__banner--name-large">Hayley Matthews</div></a>
</div>
</div>
</td>
<td>
<div class="rankings-block__banner--nationality">
<div class="flag-15 WI"></div>
<span class="rankings-block__banner--nation"></span>WI
</div>
</td>
<td class="u-text-left">
<div class="rankings-block__banner--rating">373</div>
</td>
<td class="u-text-right u-hide-phablet u-overflow-hidden">
<div class="rankings-block__career-best">
<span class="rankings-block__career-best-text">
                                383 v England, 04/12/2022
                        </span>
<span class="circle-branding circle-branding--full-table circle-branding--top"></span>
<span class="circle-branding circle-branding--full-table circle-branding--bottom"></span>
</div>
</td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    2
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/1800">Natalie Sciver</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>
<td class="table-body__cell rating">371</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                395 v South Africa, 11/07/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    3
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/471">Ellyse Perry</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>
<td class="table-body__cell rating">366</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                548 v West Indies, 11/09/2019
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    4
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/424">Marizanne Kapp</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SA"></span>
<span class="table-body__logo-text">SA</span>
</td>
<td class="table-body__cell rating">349</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                419 v West Indies, 10/09/2021
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    5
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/3756">Amelia Kerr</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo NZ"></span>
<span class="table-body__logo-text">NZ</span>
</td>
<td class="table-body__cell rating">336</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                356 v West Indies, 25/09/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    6
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/3192">Deepti Sharma</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo IND"></span>
<span class="table-body__logo-text">IND</span>
</td>
<td class="table-body__cell rating">322</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                397 v South Africa, 09/10/2019
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    7
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/4128">Ashleigh Gardner</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>
<td class="table-body__cell rating">292</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                292 v Pakistan, 21/01/2023
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    8
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/468">Jess Jonassen</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo AUS"></span>
<span class="table-body__logo-text">AUS</span>
</td>
<td class="table-body__cell rating">250</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                308 v West Indies, 11/09/2019
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    9
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/636">Nida Dar</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo PAK"></span>
<span class="table-body__logo-text">PAK</span>
</td>
<td class="table-body__cell rating">232</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                232 v Australia, 21/01/2023
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    10
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/3337">Sophie Ecclestone</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>
<td class="table-body__cell rating">205</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                217 v South Africa, 31/03/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    11
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/478">Sophie Devine</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo NZ"></span>
<span class="table-body__logo-text">NZ</span>
</td>
<td class="table-body__cell rating">201</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                305 v Australia, 05/10/2020
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    12
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/1013">Chloe-Lesleigh Tryon</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SA"></span>
<span class="table-body__logo-text">SA</span>
</td>
<td class="table-body__cell rating">197</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                197 v England, 18/07/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    13
                                </span>
<div class="ranking-pos up">
<svg class="icon">
<use xlink:href="/resources/prod/v8.30.0/i/svg-output/icons.svg#icn-chevron-up" xmlns:xlink="http://www.w3.org/1999/xlink"></use>
</svg>
<span class="ranking-pos__change-amount">(3)</span>
<span class="ranking-pos__tooltip">This player has moved up in the rankings since the previous rankings update</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/600">Chamari Athapaththu</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SL"></span>
<span class="table-body__logo-text">SL</span>
</td>
<td class="table-body__cell rating">195</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                195 v Bangladesh, 04/05/2023
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    =
                                </span>
<div class="ranking-pos down">
<svg class="icon">
<use xlink:href="/resources/prod/v8.30.0/i/svg-output/icons.svg#icn-chevron-down" xmlns:xlink="http://www.w3.org/1999/xlink"></use>
</svg>
<span class="ranking-pos__change-amount">(1)</span>
<span class="ranking-pos__tooltip">This player has moved down in the rankings since the previous rankings update</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/547">Katherine Brunt</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>
<td class="table-body__cell rating">195</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                296 v Australia, 03/02/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    15
                                </span>
<div class="ranking-pos down">
<svg class="icon">
<use xlink:href="/resources/prod/v8.30.0/i/svg-output/icons.svg#icn-chevron-down" xmlns:xlink="http://www.w3.org/1999/xlink"></use>
</svg>
<span class="ranking-pos__change-amount">(1)</span>
<span class="ranking-pos__tooltip">This player has moved down in the rankings since the previous rankings update</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/573">Stafanie Taylor</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo WI"></span>
<span class="table-body__logo-text">WI</span>
</td>
<td class="table-body__cell rating">181</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                559 v New Zealand, 10/10/2013
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    16
                                </span>
<div class="ranking-pos down">
<svg class="icon">
<use xlink:href="/resources/prod/v8.30.0/i/svg-output/icons.svg#icn-chevron-down" xmlns:xlink="http://www.w3.org/1999/xlink"></use>
</svg>
<span class="ranking-pos__change-amount">(1)</span>
<span class="ranking-pos__tooltip">This player has moved down in the rankings since the previous rankings update</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/1830">Rumana Ahmed</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo BAN"></span>
<span class="table-body__logo-text">BAN</span>
</td>
<td class="table-body__cell rating">176</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                198 v South Africa, 05/03/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    17
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/">Charlotte Dean</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo ENG"></span>
<span class="table-body__logo-text">ENG</span>
</td>
<td class="table-body__cell rating">174</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                184 v West Indies, 04/12/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    18
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/428">Sune Luus</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo SA"></span>
<span class="table-body__logo-text">SA</span>
</td>
<td class="table-body__cell rating">171</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                223 v Ireland, 17/06/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    19
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/1818">Salma Khatun</a>
</td>
<td class="table-body__cell nationality-logo rankings-table__team">
<span class="flag-15 table-body_logo BAN"></span>
<span class="table-body__logo-text">BAN</span>
</td>
<td class="table-body__cell rating">162</td>
<td class="table-body__cell u-text-right u-hide-phablet">
                                170 v Australia, 25/03/2022
                        </td>
</tr>
<tr class="table-body">
<td class="table-body__cell table-body__cell--position u-text-right">
<div class="rankings-table__pos-container">
<span class="rankings-table__pos-number">
                                    20
                                </span>
<div class="ranking-pos no-change">
<span class="ranking-pos__no-change-line"></span>
<span class="ranking-pos__change-amount">(0)</span>
</div>
</div>
</td>
<td class="table-body__cell rankings-table__name name">
<a href="/rankings/womens/player-rankings/559">Harmanpreet Kaur</a>
</td>

In [8]:
name=soup.find_all('td',class_='table-body__cell rankings-table__name name')
name

[<td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1800">Natalie Sciver</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/471">Ellyse Perry</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/424">Marizanne Kapp</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3756">Amelia Kerr</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3192">Deepti Sharma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4128">Ashleigh Gardner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/468">Jess Jonassen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/636">Nida Dar</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3337">Sophie Ecclestone</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/478">Sophie Devine</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1013">Chloe-Lesleigh Tryon</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/600">Chamari Athapaththu</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/547">Katherine Brunt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/573">Stafanie Taylor</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1830">Rumana Ahmed</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/">Charlotte Dean</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/428">Sune Luus</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1818">Salma Khatun</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/559">Harmanpreet Kaur</a>
 </td>]

In [12]:
rating=soup.find_all('td',class_='table-body__cell rating')
rating

[<td class="table-body__cell rating">371</td>,
 <td class="table-body__cell rating">366</td>,
 <td class="table-body__cell rating">349</td>,
 <td class="table-body__cell rating">336</td>,
 <td class="table-body__cell rating">322</td>,
 <td class="table-body__cell rating">292</td>,
 <td class="table-body__cell rating">250</td>,
 <td class="table-body__cell rating">232</td>,
 <td class="table-body__cell rating">205</td>,
 <td class="table-body__cell rating">201</td>,
 <td class="table-body__cell rating">197</td>,
 <td class="table-body__cell rating">195</td>,
 <td class="table-body__cell rating">195</td>,
 <td class="table-body__cell rating">181</td>,
 <td class="table-body__cell rating">176</td>,
 <td class="table-body__cell rating">174</td>,
 <td class="table-body__cell rating">171</td>,
 <td class="table-body__cell rating">162</td>,
 <td class="table-body__cell rating">157</td>]

In [17]:
team=soup.find_all('span',class_='table-body__logo-text')
team

[<span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">IND</span>]

In [18]:
df=pd.DataFrame({'Name':name,'Rating':rating,'Team':team})
print(df)

                                Name Rating   Team
0         [\n, [Natalie Sciver], \n]  [371]  [ENG]
1           [\n, [Ellyse Perry], \n]  [366]  [AUS]
2         [\n, [Marizanne Kapp], \n]  [349]   [SA]
3            [\n, [Amelia Kerr], \n]  [336]   [NZ]
4          [\n, [Deepti Sharma], \n]  [322]  [IND]
5       [\n, [Ashleigh Gardner], \n]  [292]  [AUS]
6          [\n, [Jess Jonassen], \n]  [250]  [AUS]
7               [\n, [Nida Dar], \n]  [232]  [PAK]
8      [\n, [Sophie Ecclestone], \n]  [205]  [ENG]
9          [\n, [Sophie Devine], \n]  [201]   [NZ]
10  [\n, [Chloe-Lesleigh Tryon], \n]  [197]   [SA]
11   [\n, [Chamari Athapaththu], \n]  [195]   [SL]
12       [\n, [Katherine Brunt], \n]  [195]  [ENG]
13       [\n, [Stafanie Taylor], \n]  [181]   [WI]
14          [\n, [Rumana Ahmed], \n]  [176]  [BAN]
15        [\n, [Charlotte Dean], \n]  [174]  [ENG]
16             [\n, [Sune Luus], \n]  [171]   [SA]
17          [\n, [Salma Khatun], \n]  [162]  [BAN]
18      [\n, [Harmanpreet Kaur], \n]  [157]  [IND]

In [19]:
df

                                Name Rating   Team
0         [\n, [Natalie Sciver], \n]  [371]  [ENG]
1           [\n, [Ellyse Perry], \n]  [366]  [AUS]
2         [\n, [Marizanne Kapp], \n]  [349]   [SA]
3            [\n, [Amelia Kerr], \n]  [336]   [NZ]
4          [\n, [Deepti Sharma], \n]  [322]  [IND]
5       [\n, [Ashleigh Gardner], \n]  [292]  [AUS]
6          [\n, [Jess Jonassen], \n]  [250]  [AUS]
7               [\n, [Nida Dar], \n]  [232]  [PAK]
8      [\n, [Sophie Ecclestone], \n]  [205]  [ENG]
9          [\n, [Sophie Devine], \n]  [201]   [NZ]
10  [\n, [Chloe-Lesleigh Tryon], \n]  [197]   [SA]
11   [\n, [Chamari Athapaththu], \n]  [195]   [SL]
12       [\n, [Katherine Brunt], \n]  [195]  [ENG]
13       [\n, [Stafanie Taylor], \n]  [181]   [WI]
14          [\n, [Rumana Ahmed], \n]  [176]  [BAN]
15        [\n, [Charlotte Dean], \n]  [174]  [ENG]
16             [\n, [Sune Luus], \n]  [171]   [SA]
17          [\n, [Salma Khatun], \n]  [162]  [BAN]
18      [\n, [Harmanpreet Kaur], \n]  [157]  [IND]

In [20]:
df.head(10)

                            Name Rating   Team
0     [\n, [Natalie Sciver], \n]  [371]  [ENG]
1       [\n, [Ellyse Perry], \n]  [366]  [AUS]
2     [\n, [Marizanne Kapp], \n]  [349]   [SA]
3        [\n, [Amelia Kerr], \n]  [336]   [NZ]
4      [\n, [Deepti Sharma], \n]  [322]  [IND]
5   [\n, [Ashleigh Gardner], \n]  [292]  [AUS]
6      [\n, [Jess Jonassen], \n]  [250]  [AUS]
7           [\n, [Nida Dar], \n]  [232]  [PAK]
8  [\n, [Sophie Ecclestone], \n]  [205]  [ENG]
9      [\n, [Sophie Devine], \n]  [201]   [NZ]